# https://docs.deno.com/runtime/reference/continuous_integration/
name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Handle line endings for Windows compatibility
      - name: Configure line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --allow-all
